services:
  postgres:
    image: postgres:16-alpine
    container_name: booking-manager-db
    environment:
      POSTGRES_DB: booking_manager_db
      POSTGRES_USER: booking_manager_user
      POSTGRES_PASSWORD: booking_manager_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
